path: C:/Users/saiko/Desktop/GithubRepo/apachi_detection/Final_data/  # dataset root dir
train: train/images  # train images (relative to 'path')
val: validation/images  # val images (relative to 'path')

# Classes
names:
  0: alpaca
